// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	if(getdvar("mapname")=="estate")
	{
	a[0] = "head_vil_shepherd";
	a[1] = "head_hero_ghost_forest";
	}
	else
	{
	a[0] = "head_tf141_forest_a";
	a[1] = "head_tf141_forest_b";
	}
	a[2] = "head_tf141_forest_c";
	a[3] = "head_tf141_forest_d";
	return a;
}
